---
  - name: Upload tar.gz Kibana from local storage
    copy:
      src: "{{ kibana_distr_name }}"
      dest: "/tmp/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
      mode: 0755
    register: get_kibana_local
    until: get_kibana_local is succeeded
    when: kibana_distr_type == 'local'
  - name: Upload tar.gz Kibana from remote URL
    get_url:
      url: "https://artifacts.elastic.co/downloads/kibana/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
      dest: "/tmp/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
      mode: 0755
      timeout: 60
      force: true
    register: get_kibana_remote
    until: get_kibana_remote is succeeded
    when: kibana_distr_type == 'remote'
  - name: Create directrory for Kibana
    become: true
    file:
      state: directory
      path: "{{ kibana_home }}"
    tags: kibana
  - name: Extract Kibana in the installation directory
    become: true
    unarchive:
      copy: false
      src: "/tmp/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
      dest: "{{ kibana_home }}"
      extra_opts: [--strip-components=1]
      creates: "{{ kibana_home }}/bin/kibana"
    tags:
      - skip_ansible_lint
      - kibana
  - name: Set environment Kibana and start
    become: true
    template:
      src: kibana.sh.j2
      dest: /etc/profile.d/kibana.sh
    tags: kibana
  - name: Open connect to kibana
    lineinfile:
      path: "{{ kibana_home }}/config/kibana.yml"
      line: 'server.host: "0.0.0.0"'
